#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Ejecutando ESLint..."
npm run lint:ci

if [ $? -ne 0 ]; then
  echo "❌ Errores de linting detectados. Corrígelos antes de hacer commit."
  exit 1
fi

echo "✅ No hay errores de linting."

echo "🧪 Ejecutando pruebas..."
npm run test:ci

if [ $? -ne 0 ]; then
  echo "❌ Las pruebas han fallado. No se permite el commit."
  exit 1
fi

echo "✅ Todas las pruebas pasaron. Procediendo con el commit..."

